name: flutter_universalad
description: A flutter plugin for TencentAD and Bytedance-UnionAD.
version: 1.0.10
homepage: https://github.com/gstory0404/flutter_universalad

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tencentad:
    git:
      url: https://github.com/kissshell/flutter_tencentad.git
  flutter_unionad:
    git:
      url: https://github.com/kissshell/flutter_unionad.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_universalad
        pluginClass: FlutterUniversaladPlugin
      ios:
        pluginClass: FlutterUniversaladPlugin
